# Coursework 1, 2026$\newcommand{\cP}{\mathcal P}\newcommand{\cA}{\mathcal A}\newcommand{\cC}{\mathcal C}\newcommand{\IV}{\mathrm{IV}}\newcommand{\Z}{\mathbb Z}$

## Instructions

**Please read** the assessment brief on the ELE page for details of submission, marking guidelines, and AI guidance.

You should work through the background material in the file `Week01.ipynb` in the Week 1 ELE tile, where it is referred to as 'Week 1 Code'.


You **must not** import any functions other than those in numpy.

Ensure you execute the following cell in order to import the required functions.

In [1]:
import numpy as np

## Q1 The Vigenère Cipher

Let $\cA = \Z/m\Z$ (for some positive integer $m$) and let $\cP = \cC = \cA^n$ (for some fixed positive integer $n$). Thus $\cP$ and $\cC$ can be seen as the set of length $n$ vectors with entries in $\cA$.

For each key $k \in \cA^n$, let the encryption function $E_k : \cP \to \cC$ be defined by
$$
E_k(b) \equiv b + k \pmod{m},
$$
where the addition is performed component-wise, modulo $m$, on the components of the vectors $b$ and $k$.

This is the **Vigenère cipher** with block length $n$, modulo $m$.

The code below is taken (with slight adaptations) from the file `Week01.ipynb` in the Week 1 ELE tile, where it is referred to as 'Week 1 Code'.

I **strongly recommend** working through the file `Week01.ipynb` before attempting the problems 

The function `str_to_int` represents a string of characters as a numpy array of integers. This isn't encryption or decryption.

In [2]:
def str_to_int(str):
    """Convert a string of characters to a numpy array of integers.
    'A' -> 0, 'B' -> 1, ..., 'Z'-> 26, '[' -> 27, ..., '`' -> 31"""
    start = ord('A')
    f = np.vectorize(lambda x : ord(x)-start)
    return f(list(str))

The function `int_to_str` represents an array of integers as a string of characters. This isn't encryption or decryption

In [3]:
def int_to_str(x):
    """Convert a numpy array of integers to a string of characters.
    0 -> 'A', 1 -> 'B', ..., 26 -> 'Z', 27 -> '[', ..., 31 -> '`'"""
    start = ord('A')
    f = np.vectorize(lambda x: chr(x + start))
    return ''.join(f(x))

For example, we can convert the numpy array $[20, 28, 31]$ of integers to a string of characters.

In [4]:
int_to_str(np.array([20, 28, 31]))

'U]`'

In [5]:
def vigenere_encrypt(k, b, m):
    """The vigenere encryption of vector b by the key k, modulo m"""
    return (k + b) % m

In this question, we work modulo $m = 32$ with block length $n = 7$.

## Question 1(a) [3 marks]

In the empty cell below, write and execute code that uses one of the above functions to give the string representation of the numpy array of integers $[0, 31, 12, 20, 5, 2, 29]$. Use the `np.array` function to create the array.

In [6]:
a = np.array([0, 31, 12, 20, 5, 2, 29]) # this is the array of integers
b = int_to_str(a) # this is the corresponding string

b

'A`MUFC^'

## Question 1(b) [3 marks]

In the empty cell below, write and execute code that uses one of the above functions to give the numeric representation of the string `HEXANE_`.

In [7]:
a = 'HEXANE_' # this is the string
b = str_to_int(a) # this is the corresponding array of integers

b

array([ 7,  4, 23,  0, 13,  4, 30])

## Question 1(c) [5 marks]

Using all the functions above, write and execute code that performs a Vigenère encryption, where the key has string representation `B_NKERS`, to encrypt the plaintext block with string representation `HEPTANE` using the key. You are working modulo 32.

Represent your answer as a string.

In [8]:
key = 'B_NKERS' # Vigenere key
plaintext = 'HEPTANE' # this is the plaintext to be encrypted

# First convert the strings to arrays of integers
int_key = str_to_int(key) 
int_plaintext = str_to_int(plaintext) 

# Now, perform Vigenere encryption and convert back into a string
int_ciphertext = vigenere_encrypt(int_key, int_plaintext, 32)  
ciphertext = int_to_str(int_ciphertext) 

ciphertext

'IC]^E_W'

To check this is correct I can use the decryption key (the additive inverse $(\text{mod} 32)$ of each integer) and it should return the original plaintext.

In [9]:
test = vigenere_encrypt((-int_key % 32), int_ciphertext, 32)  # not required to take mod 32 in the key as it gives same result 
int_to_str(test)

'HEPTANE'

## Question 2 Cipher Block Chaining mode for the Vigenère cipher

We continue with the notation from Question 1, but we will fix the modulus $m = 2^s$ for some non-negative integer $s$. We treat each integer modulo $2^s$ as a binary number of bit-length $s$.

Suppose we have a list $b_1, \dots, b_m$ of plaintext messages and suppose the ciphertext $c_1, \dots, c_m$ is constructed as follows. Let $c_0 = \IV$ and, for each $i \ge 1$, let $c_i = E(b_i \oplus c_{i-1})$, where $\oplus$ denotes the component-wise XOR of the components of the input vectors.

## Question 2(a) [5 marks]

In the cell below, write and execute code that outputs the exclusive or (XOR) of the numbers with binary representation $01101$ and $10101$. Present your answer in binary notation.

In [10]:
a = 0b01101
b = 0b10101

c = a ^ b
bin(c)

'0b11000'

## Question 2(b) [10 marks]

For the remainder of Question 2, we'll use the Vigenère cipher in CBC mode. The cipher key has string representation `^KAWAII` and the initialisation vector has string representation `[OTAKU]`.

Write and execute code to encrypt the message $b_1 \| b_2 \| b_3$, where $b_1$, $b_2$, and $b_3$, in order, have string representations `SNORLAX`, `PSYDUCK`, and `PIKACHU`.

Write and execute code that gives the string representation of the ciphertext message $c_1$, $c_2$, $c_3$.

In [11]:
str_key = '^KAWAII'
str_IV = '[OTAKU]'

str_key, str_IV

('^KAWAII', '[OTAKU]')

In [12]:
str_b1, str_b2, str_b3 = 'SNORLAX', 'PSYDUCK', 'PIKACHU'

str_b1, str_b2, str_b3

('SNORLAX', 'PSYDUCK', 'PIKACHU')

In [13]:
# Convert the strings to integers
int_key, int_IV, int_b1, int_b2, int_b3 = str_to_int(str_key), str_to_int(str_IV), str_to_int(str_b1), str_to_int(str_b2), str_to_int(str_b3)

In [14]:
# First set the function for the Vigenere cipher being used in each step
def E(x):
    """Vigenere encrypt with the global key k, modulo 32"""
    return vigenere_encrypt(int_key, x, 32)
    # double check what exactly it means by s - 32 should be sufficient for the all symbols used as they seem to go up to around 29

In [15]:
# Vigenere Cipher in CBC mode
int_c0 = int_IV
int_c1 = E(int_b1 ^ int_c0) 
int_c2 = E(int_b2 ^ int_c1) 
int_c3 = E(int_b3 ^ int_c2) 

int_c1, int_c2, int_c3

(array([ 5, 13, 29,  7,  1, 28, 19]),
 array([ 7,  9,  5, 26, 21,  6,  1]),
 array([ 5, 11, 15, 16, 23,  9, 29]))

In [16]:
# Convert ciphertext back to strings
str_c1, str_c2, str_c3 = int_to_str(int_c1), int_to_str(int_c2), int_to_str(int_c3)

str_c1, str_c2, str_c3

('FN^HB]T', 'HJF[VGB', 'FLPQXJ^')

## Question 2(c) [10 marks]

Below is skeleton code for a function `decryption_key_from_encryption_key`. It expects an encryption key $e$, expressed as a numpy array of integers. It should return $d$, the corresponding Vigenère decryption key, expressed as a numpy array of integers. The integer $m$ is the modulus for the Vigenère cipher.

Replace `None` below with an appropriate expression..

In [17]:
def decryption_key_from_encryption_key(k, m):
    """Returns the Vigenère decryption key, modulo m, that corresponds to the encryption key k"""
    return -k % m

## Question 2(d) [10 marks]

Let `k` be the encryption key (a numpy array of integers) with string representation `^KAWAII`.

Using your function `decryption_key_from_encryption_key`, or otherwise, find the decryption key, as a numpy array of integers modulo $32$, corresponding to the encryption key `k`.

In [18]:
k = int_key
k

array([29, 10,  0, 22,  0,  8,  8])

In [19]:
dk = decryption_key_from_encryption_key(int_key, 32)
dk

array([ 3, 22,  0, 10,  0, 24, 24])

I can test it has worked by applying it to the ciphertext above.

In [20]:
# Define decryption function
def D(x):
    """Vigenere encrypt with the global key k, modulo 32"""
    return vigenere_encrypt(dk, x, 32)

In [21]:
# Cipher with decryption - since it's done in CBC I have to do it in reverse
int_c0 = int_IV
int_b1 = int_c0 ^ D(int_c1)
int_b2 = int_c1 ^ D(int_c2)
int_b3 = int_c2 ^ D(int_c3)  # xor-ing twice gives back the original (i.e. a ^ b ^ a = b )

str_b1, str_b2, str_b3 = int_to_str(int_b1), int_to_str(int_b2), int_to_str(int_b3)
str_b1, str_b2, str_b3

('SNORLAX', 'PSYDUCK', 'PIKACHU')

## Question 2(e) [14 marks]

We now receive a Vigenère-CBC encrypted message with the same encryption key and initialisation vector as in Question 2(b).

The message is the concatenation $c_1 \| c_2 \| c_3$ of three ciphertext blocks. The tuple `CS` below gives the string representations of the  blocks $c_1$, $c_2$, $c_3$.

Write and execute code to recover a list of string representations of the corresponding plaintext blocks $b_1, b_2, b_3$.

**WARNING:** this isn't simply a matter of finding the Vigenère decryption of each of the ciphertext blocks. You must take CBC mode into account.

In [22]:
CS = 'WQVBOPX', 'BQRAFJJ', 'ABVHRQJ' 

Start by coverting the strings to integer representations, then I can perform the decryption as demonstrated above.

In [23]:
int_c1, int_c2, int_c3 = str_to_int(CS[0]), str_to_int(CS[1]), str_to_int(CS[2])

Since the encryption was done with CBC I have to decrypt similarly.

In [24]:
# Now to decrypt
int_c0 = int_IV
int_b1 = int_c0 ^ D(int_c1)
int_b2 = int_c1 ^ D(int_c2)
int_b3 = int_c2 ^ D(int_c3) 

In [25]:
str_b1, str_b2, str_b3 = int_to_str(int_b1), int_to_str(int_b2), int_to_str(int_b3)
str_b1, str_b2, str_b3

('DIGLETT', 'SWELLOW', 'CHERUBI')

## Question 3

We continue the ideas from Questions 1 and 2, but now with an unknown initialisation vector and an unknown key.

The plaintext blocks $b_1, b_2$ have string representations `ELBARTO` and `SIMPSON`, respectively.

The ciphertext blocks $c_1, c_2$ have string representations `WONZKED` and `ETFCGXS`, respectively.

## Question 3(a)(i) [10 marks]

Explain how to recover the initialisation vector. Give your answer in the markdown cell below (no code required).

Since we are given two consecutive plaintext and ciphertext blocks, we can derive the following relationships between the values:

$c_1 = (c_0 \oplus b_1) + k \, (\text{mod } 32)$ 

$c_2 = (c_1 \oplus b_2) + k \, (\text{mod } 32)$

If we rearrange each equation to make $k$ the subject and then equate them, that gives the following:

$c_1 - (c_0 \oplus b_1) \, (\text{mod } 32) = c_2 - (c_1 \oplus b_2) \, (\text{mod } 32) $

Now, we can rearrange for the initialisation vector $c_0$

$c_0 \, (\text{mod } 32) = (c_1 + (c_1 \oplus b_2) - c_2) \oplus b_1 \, (\text{mod } 32)$

## Question 3(a)(ii) [10 marks]

Following your argument in Question 3(a)(i), write and execute code to recover the initialisation vector. Also give the string representation of the initialisation vector. The string representation should be an English word. If not, you've made a mistake.

In [26]:
# Convert strings to integers
b1_str, b2_str, c1_str, c2_str = "ELBARTO", "SIMPSON", "WONZKED", "ETFCGXS"
b1_int, b2_int, c1_int, c2_int = str_to_int(b1_str), str_to_int(b2_str), str_to_int(c1_str), str_to_int(c2_str)

In [27]:
# Find the intialisation vector
c0_int = ((c1_int - (c2_int - (c1_int ^ b2_int))) ^ b1_int) % 32
c0_string = int_to_str(c0_int)
c0_string

'SKINNER'

## Question 3(b)(i) [10 marks]

Explain how to recover the encryption key. Give your answer in the markdown cell below (no code required).

I know that $c_2 = k + (c_1 \mathbin{\oplus} b_2) \, (\text{mod } 32) $. I can recover the key used for the Vigenere cipher by rearrangin for k:

\begin{equation}
k = c_2 - (c_1 \mathbin{\oplus} b_2) \, (\text{mod } 32)
\end{equation}

## Question 3(b)(ii) [10 marks]

Using your answers to Questions 3(b)(i) and 3(a)(ii), write and execute code to recover the encryption key. Also give the string representation of the encryption key. Again, the string representation of should be an English word. If not, you've made a mistake.

In [28]:
# Find the key
k_int = (c2_int - (c1_int ^ b2_int)) % 32
k_str = int_to_str(k_int)
k_str

'ANEMONE'

This demonstrates how even with just one block of known plaintext we can find the decryption key (assuming we know the order of the ciphertext and corresponding plaintext). With just a single block of known plaintext we could decipher all subsequent or previous blocks of ciphertext other than the first block (as that requires the initialisation vector). CBC makes the decryption more difficult as it requires us to solve each block sequentially, but this process is easy with a computer.